[package]
name = "rust-whoiser"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
moka = { version = "0.12.10", features = [ "future" ] }
whois-rust = { version = "1.6.0", features = [ "tokio" ] }
